name: kmpihole_dev
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2026.02.0
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP port
      - "80:80/tcp"
      - "443:443/tcp" # By default, FTL will generate a self-signed certificate
    network_mode: "host"
    environment:
      TZ: 'Australia/Sydney'
      FTLCONF_webserver_api_password: password
      FTLCONF_dns_upstreams: 1.1.1.1;1.0.0.1
    volumes:
      - kmpihole_dev_logs
      - kmpihole_dev_data:/etc/pihole
      - kmpihole_dev_dnsmasq:/etc/dnsmasq.d
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    restart: unless-stopped

volumes:
  kmpihole_dev_logs:
    external: true
  kmpihole_dev_data:
    external: true
  kmpihole_dev_dnsmasq:
    external: true